get:
  tags:
    - 사업계획-종합
  summary: 계획종합(상세) 정보 조회
  description: 연도별 계획종합(상세) 정보를 조회합니다.
  parameters:
    #공통 - API Key
    - $ref: '../components/commonData.yaml#/components/parameters/ApiKeyHeader'
    #계획종합 상세 - 연도
    - $ref: '../components/products_dtlData.yaml#/components/parameters/getProducts_dtlchk_year_Query'
    #계획종합 상세 - 구분
    - $ref: '../components/products_dtlData.yaml#/components/parameters/getProducts_dtlchk_gubun_Query'
  responses:
    '200':
      description: 성공적으로 계획종합(상세) 정보를 조회했습니다.
      content:
        application/json:
          schema:
            $ref: '../components/products_dtlData.yaml#/components/schemas/getProducts_dtl_Res'
    '403':
      $ref: '../components/commonData.yaml#/components/responses/InvalidKey'
    '404':
      $ref: '../components/commonData.yaml#/components/responses/NotFound'
    '500':
      $ref: '../components/commonData.yaml#/components/responses/InternalServerError' 