name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: |
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag yp:$TIMESTAMP
        docker tag yp:$TIMESTAMP ${{ secrets.DOCKER_USERNAME }}/yp:$TIMESTAMP
        docker push ${{ secrets.DOCKER_USERNAME }}/yp:$TIMESTAMP